const express = require("express")
const app = express()
const mongoose = require("mongoose")
const cors = require("cors")
require('dotenv').config()
const todos = require("./apis.js") 
const port  = process.env.PORT || 3000
const mongoUrl = process.env.MONGO_URL
app.use(cors())
app.use(express.json())
app.use("/todos",todos)
mongoose.connect(mongoUrl)
.then(()=>console.log("Connected to mongo db"))
.catch(err =>console.error(err))
app.listen(port,()=>console.log(`listening at http://localhost:${port}`))