const express = require("express")
const app = express()
const mongoose = require("mongoose")
const cors = require("cors")
const todos = require("./apis.js") 
const port  = process.env.PORT || 3000
app.use(cors())
app.use(express.json())
app.use("/todos",todos)
mongoose.connect("mongodb+srv://nziza:ZyU94l15DmjqDen3@cluster1.p6jyuxh.mongodb.net/Mytodos")
.then(()=>console.log("Connected to mongo db"))
.catch(err =>console.error(err))
app.listen(port,()=>console.log(`listening at http://localhost:${port}`))